import XCTest
@testable import Trendy

/// Golden vectors shared with web/tests/wotd.test.mjs and cli/test_wotd.py
/// (Tests/Fixtures/wotd-golden.json, regenerated by scripts/gen-wotd-golden.py).
final class WordOfTheDayTests: XCTestCase {
    private struct Golden: Decodable {
        struct Vector: Decodable { let date: String; let term: String }
        struct Seed: Decodable { let cycle: Int; let seed: UInt32 }
        struct Permutation: Decodable { let n: Int; let cycle: Int; let order: [Int] }
        struct OverrideCase: Decodable { let date: String; let term: String; let override: Bool }
        let epoch: String
        let seedBase: UInt32
        let poolSize: Int
        let pool: [String]
        let vectors: [Vector]
        let seeds: [Seed]
        let permutations: [Permutation]
        let overrides: [String: String]
        let overrideCases: [OverrideCase]
    }

    private static func fixtureURL() -> URL? {
        let env = ProcessInfo.processInfo.environment
        if let dir = env["TRENDY_FIXTURES_DIR"], !dir.isEmpty {
            return URL(fileURLWithPath: dir).appendingPathComponent("wotd-golden.json")
        }
        let bundles = [Bundle(for: WordOfTheDayTests.self), Bundle.main] + Bundle.allBundles
        if let url = bundles.lazy.compactMap({ $0.url(forResource: "wotd-golden", withExtension: "json") }).first {
            return url
        }
        let local = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent().deletingLastPathComponent()
            .appendingPathComponent("Fixtures/wotd-golden.json")
        return FileManager.default.fileExists(atPath: local.path) ? local : nil
    }

    private func golden() throws -> Golden {
        let url = try XCTUnwrap(Self.fixtureURL(), "wotd-golden.json not found")
        return try JSONDecoder().decode(Golden.self, from: Data(contentsOf: url))
    }

    private var pool: [LexiconEntry] { WordOfTheDay.buildPool(TestData.shared.slang) }

    func testPoolMatchesFixture() throws {
        let g = try golden()
        XCTAssertEqual(WordOfTheDay.epoch, g.epoch)
        XCTAssertEqual(WordOfTheDay.seedBase, g.seedBase)
        XCTAssertEqual(pool.count, g.poolSize)
        XCTAssertEqual(pool.map { $0.terms[0] }, g.pool)
    }

    func testGoldenVectors() throws {
        let g = try golden()
        let pool = self.pool
        XCTAssertGreaterThanOrEqual(g.vectors.count, 20)
        for v in g.vectors {
            XCTAssertEqual(WordOfTheDay.word(pool: pool, date: v.date)?.term, v.term, v.date)
        }
    }

    func testSeedsAndPermutations() throws {
        let g = try golden()
        for s in g.seeds {
            XCTAssertEqual(WordOfTheDay.cycleSeed(s.cycle), s.seed, "cycle \(s.cycle)")
        }
        for p in g.permutations {
            XCTAssertEqual(WordOfTheDay.cycleOrder(p.n, p.cycle), p.order, "n=\(p.n) cycle=\(p.cycle)")
        }
    }

    func testOverrides() throws {
        let g = try golden()
        let pool = self.pool
        for c in g.overrideCases {
            let w = WordOfTheDay.word(pool: pool, date: c.date, overrides: g.overrides)
            XCTAssertEqual(w?.term, c.term, c.date)
            XCTAssertEqual(w?.isOverride, c.override, c.date)
        }
        for (date, _) in TestData.shared.wotdOverrides {
            XCTAssertEqual(TestData.shared.wordOfTheDay(on: date)?.isOverride, true, date)
        }
    }

    func testEveryWordOncePerCycleWithoutBackToBackRepeats() {
        let pool = self.pool
        let n = pool.count
        XCTAssertGreaterThan(n, 2)
        for cycle in [-1, 0, 1, 2, 3] {
            XCTAssertEqual(WordOfTheDay.cycleOrder(n, cycle).sorted(), Array(0..<n))
        }
        var date = WordOfTheDay.addDays(WordOfTheDay.epoch, -3)!
        var previous: String?
        var seen = Set<String>()
        for i in 0..<(3 * n + 3) {
            let term = WordOfTheDay.word(pool: pool, date: date)!.term
            XCTAssertNotEqual(term, previous, date)
            if i >= 3 && i < 3 + n { seen.insert(term) }
            previous = term
            date = WordOfTheDay.addDays(date, 1)!
        }
        XCTAssertEqual(seen.count, n)
    }

    func testEligibility() {
        let base = LexiconEntry(terms: ["zzz"], short: "s", origin: "o")
        XCTAssertTrue(WordOfTheDay.isEligible(base))
        var e = base; e.source = "abbreve"; XCTAssertFalse(WordOfTheDay.isEligible(e))
        e = base; e.confidence = "low"; XCTAssertFalse(WordOfTheDay.isEligible(e))
        e = base; e.radarSource = "reddit"; XCTAssertFalse(WordOfTheDay.isEligible(e))
        e = base; e.wotd = false; XCTAssertFalse(WordOfTheDay.isEligible(e))
        e = base; e.mature = true; XCTAssertFalse(WordOfTheDay.isEligible(e))
        e = base; e.origin = ""; XCTAssertFalse(WordOfTheDay.isEligible(e))
        e = base; e.explain = "a hookup thing"; XCTAssertFalse(WordOfTheDay.isEligible(e))
        e = base; e.explain = "What The F***"; XCTAssertFalse(WordOfTheDay.isEligible(e))
        e = base; e.terms = ["edging"]; XCTAssertFalse(WordOfTheDay.isEligible(e))
        e = base; e.explain = "Sussex essays"; XCTAssertTrue(WordOfTheDay.isEligible(e))
        let terms = Set(pool.flatMap { $0.terms.map(WordOfTheDay.normalizeTerm) })
        for bad in ["sneaky link", "gyatt", "deadass", "edging", "situationship", "wtf", "copium"] {
            XCTAssertFalse(terms.contains(bad), bad)
        }
        for entry in pool {
            XCTAssertNotNil(entry.wotdExample ?? entry.example, entry.terms[0])
        }
    }

    func testDates() {
        XCTAssertFalse(WordOfTheDay.isValidDate("2026-02-29"))
        XCTAssertTrue(WordOfTheDay.isValidDate("2028-02-29"))
        XCTAssertFalse(WordOfTheDay.isValidDate("2026-1-1"))
        XCTAssertEqual(WordOfTheDay.daysSinceEpoch("2026-01-01"), 0)
        XCTAssertEqual(WordOfTheDay.daysSinceEpoch("2025-12-31"), -1)
        XCTAssertEqual(WordOfTheDay.addDays("2026-12-31", 1), "2027-01-01")
        XCTAssertEqual(WordOfTheDay.addDays("2024-03-01", -1), "2024-02-29")
        XCTAssertNil(WordOfTheDay.word(pool: pool, date: "2026-13-01"))
        let utc = TimeZone(identifier: "UTC")!
        let instant = Date(timeIntervalSince1970: 1_791_500_000) // 2026-10-08T22:53:20Z
        XCTAssertEqual(WordOfTheDay.localDateString(instant, timeZone: utc), "2026-10-08")
        XCTAssertEqual(WordOfTheDay.localDateString(instant, timeZone: TimeZone(secondsFromGMT: 3 * 3600)!), "2026-10-09")
    }

    func testCardAndShareText() throws {
        let w = try XCTUnwrap(WordOfTheDay.word(pool: pool, date: "2026-10-08", overrides: ["2026-10-08": "six seven"]))
        XCTAssertEqual(w.term, "six seven")
        let card = WordOfTheDay.card(for: w, trends: TestData.shared.trends)
        XCTAssertNotNil(card.example)
        XCTAssertNotNil(card.trend, "67 is also a trend")
        XCTAssertEqual(card.whoSaysThis, "Gen Alpha \u{2014} mostly kids/tweens right now")
        XCTAssertTrue(card.shareText.hasPrefix("Trendy word of the day: six seven \u{2014} "))
        XCTAssertTrue(card.shareText.hasSuffix(" https://bluenightlightpup.github.io/trendy/app/"))
        XCTAssertEqual(WordOfTheDay.displayTerm("w"), "W")
        XCTAssertEqual(WordOfTheDay.quoteExample("This slaps."), "\u{201C}This slaps.\u{201D}")
        XCTAssertEqual(WordOfTheDay.quoteExample("\u{201C}Bet.\u{201D}"), "\u{201C}Bet.\u{201D}")
    }
}
