#!/usr/bin/env python3
"""Regenerate Tests/Fixtures/wotd-golden.json from cli/wotd.py and web/data.

Run this after curating slang.json in a way that changes the Word of the Day pool (new curated
entries, `wotd: false`, new safety words). The JS (web/tests/wotd.test.mjs), Python
(cli/test_wotd.py) and Swift (Tests/TrendyTests/WordOfTheDayTests.swift) suites then all have to
agree with the new vectors. Radar candidates never enter the pool, so the daily ingest can't
change it.

  python3 scripts/gen-wotd-golden.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from cli import wotd  # noqa: E402

DATES = [
    "2024-02-29", "2025-12-31", "2026-01-01", "2026-01-02", "2026-04-14", "2026-04-15",
    "2026-07-04", "2026-10-08", "2026-10-09", "2026-10-10", "2026-10-11", "2026-10-12",
    "2026-10-13", "2026-10-14", "2026-10-31", "2026-12-25", "2027-01-01", "2027-03-14",
    "2028-02-29", "2030-06-15", "2040-11-03", "2099-12-31",
]


def main() -> int:
    slang = json.loads((ROOT / "web/data/slang.json").read_text(encoding="utf-8"))
    pool = wotd.build_pool(slang)
    n = len(pool)
    vectors = [{"date": d, "term": wotd.word_for_date(slang, d, overrides={}, pool=pool)["term"]} for d in DATES]
    # Both sides of the first cycle boundaries (slot N-1 → slot 0).
    for k in (1, 2):
        last = wotd.add_days("2026-01-01", k * n - 1)
        first = wotd.add_days(last, 1)
        for d in (last, first):
            vectors.append({"date": d, "term": wotd.word_for_date(slang, d, overrides={}, pool=pool)["term"]})
    vectors = sorted({v["date"]: v for v in vectors}.values(), key=lambda v: v["date"])
    pick = {"2026-10-08": "rizz", "2026-12-25": "W", "2026-12-31": "not-a-real-term-xyz"}
    override_cases = []
    for d in ("2026-10-08", "2026-12-25", "2026-12-31"):
        w = wotd.word_for_date(slang, d, overrides={"overrides": pick}, pool=pool)
        override_cases.append({"date": d, "term": w["term"], "override": w["override"]})
    doc = {
        "about": "Golden vectors for the Word of the Day algorithm (docs/word-of-the-day.md). "
                 "Generated by scripts/gen-wotd-golden.py; checked by the JS, Python and Swift tests.",
        "epoch": wotd.EPOCH.isoformat(),
        "seedBase": wotd.SEED_BASE,
        "poolSize": n,
        "pool": [wotd.terms_of(e)[0] for e in pool],
        "vectors": vectors,
        "seeds": [{"cycle": c, "seed": wotd.cycle_seed(c)} for c in (-2, -1, 0, 1, 2, 7, 1000)],
        "permutations": [
            {"n": n2, "cycle": c, "order": wotd.cycle_order(n2, c)}
            for n2, c in ((10, 0), (10, 1), (10, -1), (7, 5), (3, 2), (1, 0))
        ],
        "overrides": pick,
        "overrideCases": override_cases,
    }
    out = ROOT / "Tests/Fixtures/wotd-golden.json"
    out.write_text(json.dumps(doc, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)}: pool {n}, {len(vectors)} vectors")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
